name: compas_ml_surrogate
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::numpy=1.19.2
  - conda-forge::pip=21.0.1
  - conda-forge::python=3.9
  - pandas
  - pip:
      - matplotlib>=3.4.3
      - git+https://github.com/COMPAS-Surrogate/ogc4_interface.git
      - git+https://github.com/TeamCOMPAS/COMPAS.git